apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mysteryImage
  name: mystery-image
spec:
  containers:
  - image: busybox
    name: mystery-image
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
